### ISSUE TITLE
QR import misreads encryption method

### ISSUE THREAD

**Issue by henrypijames** [d4boy/v2rayNG#3]
Importing setting via QR code (generated by v2rayN on Windows), everything else is correct, but `vmess security`, which should be `aes-128-gcm`, ends up as `chacha20-poly1305`. Has the import function simply missed the security option?

**Comment by d4boy** [comment]
yes, security option is ignored
"Chacha20-poly1305": Recommended for use on the mobile side

**Comment by henrypijames** [comment]
But client must follow server, not the other way around. If server is configured to use AES, "recommending" Chacha to the client makes no sense.

**Comment by henrypijames** [comment]
OK, my bad. I thought the encryption methods have to match. I didn't understand that encryption is not defined on the server, and the server can use different encryption methods with different clients depending on client config.

**Comment by d4boy** [comment]
yes
server  automatic identification, no configuration
https://www.v2ray.com/chapter_02/protocols/vmess.html
